AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  hello
  Sample SAM Template for sam-tutorial

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Layers:
        - !Ref HelloWorldLayer
      Events:
        ScheduledFunction:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 12 * * ? *)
            ScheduleExpressionTimezone: Asia/Tokyo
            Name: !Sub ${HelloWorldFunction}-scheduler
            Description: Scheduled event for hello world

  HelloWorldLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: HelloWorldLayer
      Description: A layer for hello world
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldFunction:
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Value: !GetAtt HelloWorldFunctionRole.Arn
