name: sam-python-cd

on:
  # push:
  #   branches:
  #     - "main"
  #   paths:
  #     - "aws/sam-cicd/sample-python/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "aws/sam-cicd/sample-python/**"

jobs:
  deploy:
    defaults:
      run:
        working-directory: aws/sam-cicd/sample-python
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup aws-sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.IAM_ROLE_ARN}}
          role-session-name: ${{github.sha}}
      - uses: actions/setup-python@v5
        with:
          python-version-file: aws/sam-cicd/sample-python/.python-version
      - name: Build & Deploy
        run: |
          sam build
          sam deploy --s3-bucket ${{secrets.S3_BUCKET}} --no-confirm-changeset
